[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.normal]
    black = '0x1e2127'
    red = '0xe06c75'
    green = '0x98c379'
    yellow = '0xd19a66'
    blue = '0x61afef'
    magenta = '0xc678dd'
    cyan = '0x56b6c2'
    white = '0x828791'

[colors.dim]
  black = "0x1e2127"
  red = "0xe06c75"
  green = "0x98c379"
  yellow = "0xd19a66"
  blue = "0x61afef"
  magenta = "0xc678dd"
  cyan = "0x56b6c2"
  white = "0x828791"

[colors.primary]
background = "0x1e2127"
foreground = "0xabb2bf"
bright_foreground = "0xe6efff"

[font]
size = 11.8

[font.normal]
family = "JetBrains Mono Nerd Font"
style= "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 1
y = 1

[window]
decorations = "none"
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 4
y = 4

[shell]
program = "/bin/fish"
args = ["-l"]
