require("config.options")
require("config.keymaps")
require("config.pack")
require("config.lsp")

-- Plugins Config
require("plugins.colorscheme")
require("plugins.alpha")
require("plugins.nvimtree")
require("plugins.bufdelete")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.noice")
require("plugins.conform")
require("plugins.gitsigns")
require("plugins.indentline")
require("plugins.markdown")
require("plugins.cmp")
require("plugins.ytplayer")
