#!/bin/sh

riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"

riverctl spawn "waybar"
riverctl spawn "~/.config/river/scripts/wallpaper_changer &"
riverctl spawn "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &"

riverctl map normal Super Q close

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Move focused view. View will be set to floating.
riverctl map normal Super+Shift Left move left 100
riverctl map normal Super+Shift Down move down 100
riverctl map normal Super+Shift Up move up 100
riverctl map normal Super+Shift Right move right 100

# Resize focused view. View will be set to floating.
riverctl map normal Super+Alt Left resize horizontal -100
riverctl map normal Super+Alt Up resize vertical 100
riverctl map normal Super+Alt Down resize vertical -100
riverctl map normal Super+Alt Right resize horizontal 100

# Snap focused view to screen edge. View will be set to floating.
riverctl map normal Super+Control Left snap left
riverctl map normal Super+Control Down snap down
riverctl map normal Super+Control Up snap up
riverctl map normal Super+Control Right snap right

riverctl map normal Super E spawn "~/.config/river/scripts/power_menu"
riverctl map normal Super D spawn fuzzel
riverctl map normal Control+Alt B spawn brave
riverctl map normal Control+Alt G spawn google-chrome-stable
riverctl map normal Control+Alt T spawn "ghostty +new-window"
riverctl map normal Control+Alt M spawn "mpv --player-operation-mode=pseudo-gui"
riverctl map normal None Print spawn 'IMG=~/images/$(date | sed "s/\s/-/g" | sed "s/--/-/g").png && grim -g "$(slurp)" $IMG && cat $IMG | wl-copy && notify-send "Success!" "Screenshot has been saved and copied to your clipboard." -u normal'

for mode in normal locked
do
  riverctl map -repeat $mode None XF86AudioRaiseVolume spawn 'pamixer --increase 1'
  riverctl map -repeat $mode None XF86AudioLowerVolume spawn 'pamixer --decrease 1'
  riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
  riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl s +1%'
  riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl s 1%-'
done

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Space toggle-float
riverctl map normal Super Return zoom # bump focused view on top of stack
riverctl map normal Super F toggle-fullscreen

# set location of main area in the layout
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

# Modify the number of views in main count
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count -1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count +1"

# Modify the ratio of the main area to total layout area
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.1"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.1"

for i in $(seq 1 6)
do
  tags=$((1 << ($i - 1)))
  riverctl map normal Super $i set-focused-tags $tags # focus the tag
  riverctl map normal Super+Shift $i set-view-tags $tags # move the focused view to specified tag
  riverctl map normal Super+Control $i toggle-focused-tags $tags # used to show the views from more than one tag at once
  riverctl map normal Super+Alt $i toggle-view-tags $tags # used to show the focused view in more than one tag
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl default-attach-mode bottom

riverctl border-color-focused 0x59acff

riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-output-change # disabled(default) | on-output-change | on-focus-change

riverctl set-repeat 50 300

touchpad="$(riverctl list-inputs | grep -i touchpad)"
riverctl input $touchpad events enabled
riverctl input $touchpad tap enabled
riverctl input $touchpad natural-scroll enabled
riverctl input $touchpad drag enabled
riverctl input $touchpad drag-lock enabled

riverctl default-layout rivertile
riverctl spawn "rivertile -outer-padding 4 -view-padding 4"
