#!/bin/sh

STATE=`awk 'NR==1{print $2}' ~/.config/scripts/data.txt`

if [[ $STATE == "disabled" ]]; then
  dunstify -u critical 'Suspend!' '<span fgcolor=\"black\">About to suspend in a minute.</span>'
fi

