#!/bin/sh

STATUS=`bluetoothctl show | grep "Powered" | grep -v "grep" | awk '{print $2}'`

if [[ $STATUS == "yes" ]];then
  bluetoothctl power off 
  dunstify -u normal "Success!" "<span fgcolor='black'>Bluetooth is disabled successfully.</span>"
elif [[ $STATUS == "no" ]];then
  bluetoothctl power on 
  dunstify -u normal "Success!" "<span fgcolor='black'>Bluetooth is enabled successfully.</span>"
fi
