#!/bin/sh

choice=$(printf "  Lock\n  Kill User Session\n󰍛  Suspend\n󰑙  Reboot\n  Power Off" | fuzzel --dmenu)

if [[ $choice == "  Lock" ]];then
  swaylock
elif [[ $choice == "  Kill User Session" ]];then
  pkill -KILL -u "$USER"
elif [[ $choice == "󰍛  Suspend" ]];then
  systemctl suspend
  swaylock 
elif [[ $choice == "󰑙  Reboot" ]];then
  systemctl reboot
elif [[ $choice == "  Power Off" ]];then
  systemctl poweroff
fi
