#!/bin/sh

STATUS=`bluetoothctl show | grep "Powered" | awk '{print $2}'`

if [[ $STATUS == "yes" ]];then
  bluetoothctl power off
  dunstify -u normal "Success!" "<span>Bluetooth is disabled successfully.</span>"
elif [[ $STATUS == "no" ]];then
  bluetoothctl power on
  dunstify -u normal "Success!" "<span>Bluetooth is enabled successfully.</span>"
fi
